services:
  postgres:
    image: postgres:latest
    container_name: postgres-uplifting-api
    ports:
      - "5401:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ~/databases/uplifting-api-postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
